### ISSUE TITLE
Error while deobfuscating

### ISSUE THREAD

**Issue by gamersindo1223** [lorenzoferre/deobfuscator#26]
| Q                        | A
| ------------------------ | ---
| Bug report ?            | Yes 
| Feature request ?          | No
**Describe:**

Hi while trying to deobfuscate the code that I input, 
**Current behavior:**

Crashed with this stack:
```javascript
/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/family.js:232
function get(key, context = true) {
            ^

RangeError: unknown file: Maximum call stack size exceeded
    at NodePath.get (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/family.js:232:13)
    at NodePath.replaceExpressionWithStatements (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/replacement.js:154:57)
    at NodePath.insertAfter (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/modification.js:148:17)
    at NodePath.replaceWithMultiple (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/replacement.js:57:22)
    at PluginPass.SequenceExpression (file:///workspace/Gitpod-Blank/node_modules/javascript-deob/src/techniques/statics/transform-sequence-expression.js:14:14)
    at newFn (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21)
    at TraversalContext.visitQueue (/workspace/Gitpod-Blank/node_modules/@babel/traverse/lib/context.js:91:21) {
  code: 'BABEL_TRANSFORM_ERROR'
}
```

**Expected behavior:**
```javascript
Code deobfuscated successfully
```

**Possible solution:**

```javascript
A fix, or support that could help me deobfuscate  the code
```

**Comment by lorenzoferre** [comment]
Hi, could you share your deobfuscated code or just the portion that causes that error?

**Comment by Glassback** [comment]
Hello @lorenzoferre, struggling with similar problems.
Can you accept my invite on LinkedIn?

**Comment by lorenzoferre** [comment]
> Hello @lorenzoferre, struggling with similar problems.
> 
> Can you accept my invite on LinkedIn?

I do not have Linkedin.
If I send my Discord username, could you reach me there?

**Comment by Glassback** [comment]
Yes. 😊

**Comment by lorenzoferre** [comment]
> Yes. 😊

Thank you.
My Discord username is: loref3rr3

**Comment by Glassback** [comment]
Invite sent. My discord is glassback

**Comment by lorenzoferre** [comment]
@gamersindo1223 I have just published a new release in which some errors have been fixed. I would appreciate it if you let me know if this version resolves your problems.

**Comment by gamersindo1223** [comment]
Thanks, but I've list the code Im trying to deobfuscate, I will provide a new update if I found the code that I was trying to deob
